#!/usr/bin/env bash
set -e

function help {
  echo 'Usage: gh-delete-artifacts -o <org> [-r <repo>] [-w <workflow>] [-n <run>]'
  exit 0
}

deleted_artifacts=0  # Counter variable

while getopts "o:r:w:n:" opt; do
  case ${opt} in
    o|org )
      org=$OPTARG
      ;;
    r|repo )
      repo=$OPTARG
      ;;
    w|workflow )
      workflow=$OPTARG
      ;;
    n|run )
      run=$OPTARG
      ;;
    \? )
      help
      ;;
  esac
done

if ! command -v gh &> /dev/null
then
    echo "GitHub CLI (gh) could not be found. Please install it first."
    exit
fi

if [[ -z "$org" ]]; then
  echo "Organization is not specified."
  help
fi

if [[ -n "$repo" ]]; then
  workflows=$(gh api repos/$org/$repo/actions/workflows --jq '.workflows[] | .id')
else
  workflows=$(gh api orgs/$org/actions/workflows --jq '.workflows[] | .id')
fi

echo "Looking for artifacts for:"
for workflow_id in $workflows; do
  if [[ -n "$workflow" && "$workflow_id" != "$workflow" ]]; then
    continue
  fi
  echo "Workflow ID: $workflow_id"
  runs=$(gh api repos/$org/$repo/actions/workflows/$workflow_id/runs --jq '.workflow_runs[] | .id')
  for run_id in $runs; do
    if [[ -n "$run" && "$run_id" != "$run" ]]; then
      continue
    fi
    echo "Run ID: $run_id"
    artifact_urls=$(gh api repos/$org/$repo/actions/runs/$run_id/artifacts --jq '.artifacts[] | .url')
    for artifact_url in $artifact_urls; do
      echo "DELETE $artifact_url"
      gh api --method DELETE $artifact_url
      ((deleted_artifacts++))  # Increment the counter variable
    done
  done
done

echo "Total artifacts deleted: $deleted_artifacts"  # Print the total number of deleted artifacts
